StudentDashboard/Models/Appraisal.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WebApplication1.Models
{
    public class Appraisal
    {
        [Editable(false)]
        [Required]
        public int EmployeeId { get; set; }
        [Required(ErrorMessage ="Enter appraiser name !!")]
        [Display(Name ="Appraiser Name")]
        public string Appraiser { get; set; }
        [Display(Name ="Appraisee Name")]
        [RegularExpression(@"^\d")]
        public string Appraisee { get; set; }
        [Range(1,5)]
        public int? Rating { get; set; }
        public bool Applicable { get; set; }
    }
}

StudentDashboard/Controllers/AppraisalController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using WebApplication1.Business;
using WebApplication1.Filters;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    [CustomHandlerError(View = "Error")]
    public class AppraisalController : Controller
    {
        public AppraisalController()
        {
            //BusinessObject = new DomainEntities();
        }

        //[HandleError(View = "Error")]
        //[CustomHandlerError(View ="Error")]
        
        public ViewResult Index()
        {
            //return RedirectToAction("Create");
            //throw new System.Exception();
            List<Appraisal> listAppraisal = null;
            try
            {
                ViewBag.Title = "Appraisals";
                listAppraisal = DomainEntities.Instance.GetAll();
                var error = TempData["Errorid"];
                throw new NullReferenceException("Bhagat raised a exception");

            }
            catch (Exception ex)
            {
                //Log.Error(ex.Message);
                //return View("Error");
                //throw;
            }
            return View(listAppraisal);
        }

        //[CustomHandlerError(View ="CustomError")]
        public ActionResult WebForm1()
        {
            return View();
        }
       
        public ActionResult Details(int id)
        {
            return View();
        }
        
        public ActionResult Create()
        {
            
            return View();
        }

        [HttpPost]
        public ActionResult Create([Bind(Exclude = "Rating")]Appraisal model)
        {
            try
            {
                //business validation rules
                
                if (ModelState.IsValid)
                {
                    var item = DomainEntities.Appraisals.Find(m => m.EmployeeId == model.EmployeeId);
                    if (item != null) return View(model);
                    model.Rating = new System.Random().Next(1, 5);
                    DomainEntities.Appraisals.Add(model);

                    return RedirectToAction("Index");
                }
                else
                {
                    return View(model);
                }
            }
            catch
            {
                return View();
            }
        }

        public JsonResult CreateAsync([Bind(Exclude = "Rating")]Appraisal model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var item = DomainEntities.Appraisals.Find(m => m.EmployeeId == model.EmployeeId);
                    if (item != null) return new JsonResult { Data = false };
                    model.Rating = new System.Random().Next(1, 5);
                    DomainEntities.Appraisals.Add(model);
                    return new JsonResult { Data = true };
                }
                else
                {
                    return new JsonResult { Data = false };
                }
            }
            catch
            {
                return new JsonResult { Data = false };
            }
        }

        public ActionResult CreateAsync1([Bind(Exclude = "Rating")]Appraisal model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var item = DomainEntities.Appraisals.Find(m => m.EmployeeId == model.EmployeeId);
                    if (item != null) return new EmptyResult();
                    model.Rating = new System.Random().Next(1, 5);
                    DomainEntities.Appraisals.Add(model);
                    return PartialView(model);
                }
                else
                {
                    return new EmptyResult();
                }
            }
            catch
            {
                return new EmptyResult();
            }
        }
        
        public ActionResult Edit(int id)
        {
            var model = DomainEntities.Instance.GetAppraisal(id);
            return View(model);
        }

        [HttpPost]
        public ActionResult Edit(Appraisal model)
        {
            try
            {
                // TODO: Add update logic here
                if (ModelState.IsValid)
                {
                    var item = DomainEntities.Appraisals.Find(m => m.EmployeeId == model.EmployeeId);
                    if (item == null) return View(model);
                    item.Appraisee = model.Appraisee;
                    item.Appraiser = model.Appraiser;
                    item.Rating = model.Rating;
                    item.Applicable = model.Applicable;
                    return RedirectToAction("Index");
                }
                else
                {
                    return View(model);
                }
            }
            catch
            {
                return View();
            }
        }
        [HttpGet]
        public ActionResult View(int id)
        {
            
                var modelvalue = DomainEntities.Instance.GetAppraisal(id);

            if (DomainEntities.Appraisals.Exists(m=>m.EmployeeId==id))
            {
                //ViewData["Errorid"] = "id";
                TempData["Errorid"] = "invalid ID";
                return RedirectToAction("Index"); 
            }

            else if (modelvalue == null)
            {
                ViewBag.AlertMsg = "Invalid Emplyoee id";
                // return RedirectToAction("Index");
                //show index screen
                //show error if any 

            }
            
            return View(modelvalue);
        }
                
            
             
            
        
        
        [HttpPost]
        public ActionResult Delete(int id)
        {
            try
            {
                //if(ModelState.IsValid)
                // {

                var item = DomainEntities.Appraisals.Find(m => m.EmployeeId == id);
                DomainEntities.Appraisals.Remove(item);



                // }


            }
            catch (Exception e)
            {
                
                ViewBag.AlertMsg= e.Message;
            }
            return RedirectToAction("Index");
        }

        public ActionResult Adresstemplete()
        {
            return PartialView();
        }
    }
}

StudentDashboard/Views/Appraisal/Adresstemplete.cshtml
<div>
    
    <input type="text" id="txtcity" />
</div>

StudentDashboard/Views/Appraisal/Create.cshtml
@model WebApplication1.Models.Appraisal

@{
    ViewBag.Title = "Create";
}
Response code : @Response.StatusCode
<h2>Create</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Appraisal</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.EmployeeId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmployeeId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmployeeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Appraiser, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Appraiser, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Appraiser, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Appraisee, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Appraisee, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Appraisee, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Applicable, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Applicable)
                    @Html.ValidationMessageFor(model => model.Applicable, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div class="form-group">
    <div class="col-md-offset-2 col-md-10">
        <input type="button" value="Create Async" class="btn btn-default" id="CreateAsync" />
    </div>
</div>
@using (Ajax.BeginForm("Create", "Appraisal", new AjaxOptions { OnSuccess = "OnAjaxSuccess" }))
{
   
    <div class="form-horizontal">
        <h4>Appraisal</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.EmployeeId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmployeeId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmployeeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Appraiser, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Appraiser, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Appraiser, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Appraisee, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Appraisee, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Appraisee, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Applicable, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Applicable)
                    @Html.ValidationMessageFor(model => model.Applicable, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div id="address_data">
            @Html.Partial("Adresstemplete");
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>

}

<div>
    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-success" })
</div>
<div id="createdAppraisal"></div>

@section scripts{ 
    
<script type="text/javascript" >
    $(document).ready(function () {
        function OnAjaxSuccess(data) {
            $("#createdAppraisal").html(data).toggle(13000);
            
            //alert(data);
            //if (data) window.location.href = '@Url.Action("Index","Appraisal")';
        }

        $("#CreateAsync").click(function (e) {
            var model = {EmployeeId:$("#EmployeeId").val(),
                Appraiser:$("#Appraiser").val(),
                Appraisee:$("#Appraisee").val(),
                Applicable:$("#Applicable").val()
            }

            $.ajax({
                url: '@Url.Action("CreateAsync1","Appraisal")',
                type: 'post',
                contentType: 'application/json',
                data: JSON.stringify(model),
                success: OnAjaxSuccess
            });
        });
        // do it ischecked ? t: f
        // func ... get request url:app, success:, error:alert('')
    });
</script>

}

StudentDashboard/Views/Appraisal/CreateAsync1.cshtml
@model WebApplication1.Models.Appraisal

@if (Model != null)
{
    <h5 class="has-success divider">Created Appraisal</h5>
    <hr/>
    <label class=""></label>
    @Html.LabelFor(m => m.Appraisee, new {@class = "label-primary col-sm-3" }) 
    @Html.DisplayFor(m => m.Appraisee, new {@class = "text-primary col-sm-5" })
}

StudentDashboard/Views/Appraisal/CreateNew.cshtml
@model WebApplication1.Models.Appraisal

@{
    ViewBag.Title = "CreateNew";
}

<h2>CreateNew</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Appraisal</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.EmployeeId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmployeeId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmployeeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Appraiser, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Appraiser, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Appraiser, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Appraisee, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Appraisee, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Appraisee, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Rating, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Rating, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Rating, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Applicable, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Applicable)
                    @Html.ValidationMessageFor(model => model.Applicable, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

StudentDashboard/Views/Appraisal/Details.cshtml
@model IEnumerable<WebApplication1.Models.Appraisal>

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.EmployeeId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Appraiser)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Appraisee)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Rating)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.EmployeeId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Appraiser)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Appraisee)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Rating)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
            @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
        </td>
    </tr>
}

</table>

StudentDashboard/Views/Appraisal/Edit.cshtml
@model WebApplication1.Models.Appraisal

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Appraisal</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.EmployeeId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmployeeId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmployeeId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Appraiser, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Appraiser, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Appraiser, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Appraisee, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Appraisee, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Appraisee, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Rating, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Rating, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Rating, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.Applicable, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Applicable)
                    @Html.ValidationMessageFor(model => model.Applicable, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

StudentDashboard/Views/Appraisal/Index.cshtml
@model IEnumerable<WebApplication1.Models.Appraisal>

<h2>@ViewBag.Title</h2>
<div>
    @Html.ActionLink("New Form", "Create")
    <hr />
    <h3>Appraisee List</h3>
    @foreach (var item in Model)
    {
        <div>
            @Html.DisplayFor(m => item.Appraisee)
            @Html.ActionLink("Edit", "Edit", "Appraisal", new { id = item.EmployeeId }, null)||
            @Html.ActionLink("View", "View", "Appraisal", new { id = item.EmployeeId }, null)
            <label  text="Label" name="errorMessage" ID="lbl" />
        </div>
    }
</div>

StudentDashboard/Views/Appraisal/View.cshtml
@model WebApplication1.Models.Appraisal

@{
    ViewBag.Title = "Delete";
    
}

<h2>Delete</h2>
@if (Model == null)
{
    @Html.Raw(ViewBag.AlertMsg)
}
else { 
<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Appraisal</h4>
    <hr />

    <dl class="dl-horizontal">
        <dt>`
            @Html.DisplayNameFor(model => model.EmployeeId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmployeeId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Appraiser)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Appraiser)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Appraisee)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Appraisee)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Rating)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Rating)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Applicable)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Applicable)
        </dd>

    </dl>
    
    @using (Html.BeginForm("Delete", "Appraisal", new { @id = Model.EmployeeId }))
    {
        @*@Html.AntiForgeryToken()*@

        <div>
            @Html.DisplayFor(model => model.EmployeeId, new { @id = Model.EmployeeId })
        </div>

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>
}